from abc import ABC, abstractmethod

class LangSpec(ABC): pass

class HighLevelLangSpec(LangSpec):
    @abstractmethod
    def import_lib(self, lib): ...
    @abstractmethod
    def default_library(self): ...
    @abstractmethod
    def indent_str(self): ...
    @abstractmethod
    def kern_start(self, name, arg_names, arg_types): ...
    @abstractmethod
    def kern_end(self): ...
    @abstractmethod
    def sequential_loop_start(self, index, start, end, step): ...
    @abstractmethod
    def parallel_loop_start(self, index, start, end, step): ...
    @abstractmethod
    def vectorized_loop_start(self, index, start, end, step): ...
    @abstractmethod
    def unrolled_loop_start(self, index, start, end, step, factor): ...
    @abstractmethod
    def gpu_block_index(self, index, start, end, step, idx): ...
    @abstractmethod
    def gpu_thread_index(self, index, start, end, step, idx): ...
    @abstractmethod
    def loop_end(self): ...
    @abstractmethod
    def if_start(self, cond): ...
    @abstractmethod
    def if_end(self): ...
    @abstractmethod
    def return_function(self): ...
    @abstractmethod
    def greater_than(self, l, r): ...
    @abstractmethod
    def index(self, a, idx): ...
    @abstractmethod
    def init(self, dt, l, r): ...
    @abstractmethod
    def assign(self, l, r): ...
    @abstractmethod
    def neg(self, a): ...
    @abstractmethod
    @abstractmethod
    def sin(self, a): ...
    @abstractmethod
    def cos(self, a): ...
    @abstractmethod
    def exp(self, a): ...
    @abstractmethod
    def log(self, a): ...
    @abstractmethod
    def sqrt(self, a): ...
    @abstractmethod
    def add(self, l, r): ...
    @abstractmethod
    def sub(self, l, r): ...
    @abstractmethod
    def mul(self, l, r): ...
    @abstractmethod
    def truediv(self, l, r): ...
    @abstractmethod
    def pow(self, l, r): ...


