from abc import ABC, abstractmethod

import dtype

class LangSpec(ABC): pass

class HighLevelLangSpec(LangSpec):
    @abstractmethod
    def import_lib(self, lib): ...
    @abstractmethod
    def default_library(self): ...
    @abstractmethod
    def indent_str(self): ...
    @abstractmethod
    def kern_start(self, name, arg_names, arg_types): ...
    @abstractmethod
    def kern_end(self): ...
    @abstractmethod
    def sequential_loop_start(self, index, start, end, step): ...
    @abstractmethod
    def parallel_loop_start(self, index, start, end, step): ...
    @abstractmethod
    def vectorized_loop_start(self, index, start, end, step): ...
    @abstractmethod
    def unrolled_loop_start(self, index, start, end, step, factor): ...
    @abstractmethod
    def gpu_block_index(self, index, start, end, step, idx): ...
    @abstractmethod
    def gpu_thread_index(self, index, start, end, step, idx): ...
    @abstractmethod
    def loop_end(self): ...
    @abstractmethod
    def if_start(self, cond): ...
    @abstractmethod
    def if_end(self): ...
    @abstractmethod
    def return_function(self): ...
    @abstractmethod
    def greater_than(self, l, r): ...
    @abstractmethod
    def index(self, a, idx): ...
    @abstractmethod
    def init(self, dt, l, r): ...
    @abstractmethod
    def assign(self, l, r): ...
    @abstractmethod
    def neg(self, a): ...
    @abstractmethod
    @abstractmethod
    def sin(self, a): ...
    @abstractmethod
    def cos(self, a): ...
    @abstractmethod
    def exp(self, a): ...
    @abstractmethod
    def log(self, a): ...
    @abstractmethod
    def sqrt(self, a): ...
    @abstractmethod
    def add(self, l, r): ...
    @abstractmethod
    def sub(self, l, r): ...
    @abstractmethod
    def mul(self, l, r): ...
    @abstractmethod
    def truediv(self, l, r): ...
    @abstractmethod
    def pow(self, l, r): ...

class CCompatibleLangSpec(HighLevelLangSpec):
    def typename(self, dt):
        if dt == dtype.int32: return "int32_t"
        elif dt == dtype.int64: return "int64_t"
        elif dt == dtype.float32: return "float"
        elif dt == dtype.float64: return "double"
        else: raise RuntimeError(f"unknown dtype: {dt}")
    def import_lib(self, lib): return f"#include <{lib}>"
    def default_library(self): return ["stdint.h", "math.h"]
    def indent_str(self): return "    "

    def kern_end(self): return "}"
    def sequential_loop_start(self, index, start, end, step): return f"for (int {index} = {start}; {index} < {end}; {index} += {step}) {{"
    def loop_end(self): return "}"
    def if_start(self, cond): return f"if ({cond}) {{"
    def if_end(self): return "}"
    def return_function(self): return "return;"
    def greater_than(self, l, r): return f"{l} <= {r}"
    def index(self, a, idx): return f"{a}[{idx}]"
    def init(self, dt, l, r): return f"{self.typename(dt)} {l} = {r};"
    def assign(self, l, r): return f"{l} = {r};"
    def neg(self, a): return f"-({a})"
    def sin(self, a): return f"sin({a})"
    def cos(self, a): return f"cos({a})"
    def exp(self, a): return f"exp({a})"
    def log(self, a): return f"log({a})"
    def sqrt(self, a): return f"sqrt({a})"
    def add(self, l, r): return f"{l} + {r}"
    def sub(self, l, r): return f"{l} - {r}"
    def mul(self, l, r): return f"{l} * {r}"
    def truediv(self, l, r): return f"{l} / {r}"
    def pow(self, l, r): return f"pow({l}, {r})"

    @abstractmethod
    def kern_start(self, name, arg_names, arg_types): ...
    @abstractmethod
    def parallel_loop_start(self, index, start, end, step): ...
    @abstractmethod
    def vectorized_loop_start(self, index, start, end, step): ...
    @abstractmethod
    def unrolled_loop_start(self, index, start, end, step, factor): ...
    @abstractmethod
    def gpu_block_index(self, index, start, end, step, idx): ...
    @abstractmethod
    def gpu_thread_index(self, index, start, end, step, idx): ...

