name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      # For flakiness test, run test multiple times
      - run: make testall
      - run: make testall
      - run: make testall
