name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          mkdir -p $HOME/tmp && cd $HOME/tmp
          git clone https://github.com/OpenMathLib/OpenBLAS.git && cd OpenBLAS
          make && make install
          ls /opt
          ls /opt/OpenBLAS
      - run: python -m venv .env && source .env/bin/activate && pip install numpy
      # For flakiness test, run test multiple times
      - run: source .env/bin/activate && go clean -testcache && make testall
      - run: source .env/bin/activate && go clean -testcache && make testall
      - run: source .env/bin/activate && go clean -testcache && make testall
